language: node_js
node_js:
  - 11.6.0
cache: npm

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --frozen-lockfile

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  on:
    branch: master
